name: Deployment CI

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Install Playwright
        run: node_modules/.bin/playwright install chromium --with-deps
      - name: Build Playground
        run: yarn run build
      - name: Run tests
        run: yarn run test
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
